# charts/docvector/Chart.yaml
apiVersion: v2
name: docvector
description: Document vectorization and RAG search platform with OpenSearch
type: application
version: 1.0.0
appVersion: "2.0.0"
keywords:
  - rag
  - opensearch
  - vectorization
  - nlp
  - ai
maintainers:
  - name: DeVops Team
    email: aecodinglocal@gmail.com
home: https://github.com/iwebbo/DocVector
sources:
  - https://github.com/iwebbo/DocVector
icon: https://raw.githubusercontent.com/iwebbo/DocVector/main/icon.png